apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-backend-config
  namespace: default
  labels:
    app: blog-backend
data:
  NODE_ENV: "production"
  OPENID_REDIRECT_URI: "http://localhost:3000/auth/callback"
  LOG_LEVEL: "info"
  API_PORT: "3001"
