apiVersion: v1
kind: Secret
metadata:
  name: blog-backend-secrets
  namespace: default
  labels:
    app: blog-backend
type: Opaque
stringData:

  openid-client-id: "mindx-onboarding"
  openid-client-secret: "cHJldmVudGJvdW5kYmF0dHJlZWV4cGxvcmVjZWxsbmVydm91c3ZhcG9ydGhhbnN0ZWU="
  # Or use base64 encoding:
  # echo -n "your-client-id" | base64
